#!/bin/bash
#Begin PBS directives for the job
#PBS -A CSC190PORT
#PBS -N gppJob
#PBS -j oe
#PBS -l walltime=0:30:00,nodes=1

#End PBS directives and begin shell commands

smallInput="512 2 2048 20"
EXEC=gppOpenMP3

cp /ccs/home/rgayatri/DOE-CSGF/${EXEC}.ex $MEMBERWORK/csc190
cd $MEMBERWORK/csc190
date

#aprun -n 1 ./${EXEC}.ex ${smallInput}

export OMP_NUM_THREADS=16
aprun -n 1 -d 16 ./${EXEC}.ex ${smallInput}
